# Generated by Django 3.1.7 on 2021-05-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('isbn_code', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=25)),
                ('publisher', models.CharField(max_length=30)),
                ('year_publish', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'buku',
                'db_table': 'buku',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('name_category', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'kategori buku',
                'db_table': 'kategori',
            },
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('handphone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('join_date', models.CharField(max_length=25)),
                ('end_date', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'pelanggan',
                'db_table': 'pelanggan',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_borrow', models.CharField(max_length=25)),
                ('end_date_borrow', models.CharField(max_length=25)),
                ('date_return', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'transaksi buku',
                'db_table': 'transaksi',
            },
        ),
    ]
